---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stack-test-deployment
  labels:
    app: stack-test
spec:
  replicas: 2  # Adjust based on load
  selector:
    matchLabels:
      app: stack-test
  template:
    metadata:
      labels:
        app: stack-test
    spec:
      containers:
        - name: stack-test-container
          image: iamtejas23/stack-test-k8s:latest  # Make sure to push this image to Docker Hub
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: stack-test-service
spec:
  type: LoadBalancer  # Expose the service externally
  selector:
    app: stack-test
  ports:
    - protocol: TCP
      port: 3000  # Exposed port
      targetPort: 3000  # Port inside the container
