apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stack-app
  name: stack-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stack-app
  template:
    metadata:
      labels:
        app: stack-app
    spec:
      containers:
      - name: cont1
        image: iamtejas23/stack-test-k8s:latest
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: stack-service
spec:
  type: LoadBalancer
  selector:
    app: stack-app
  ports:
    - port: 3000
      targetPort: 3000